version: '2'
services:
  my-traefik:
    image: traefik
    command: -c /dev/null --web --docker --docker.domain=dck.mojserver.mk
    labels:
      - "traefik.enable=false"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  my-eureka:
    image: peshou/gameit-eureka
    labels:
      - "traefik.port=8761"
      - "traefik.backend=my-eureka"
      - "traefik.frontend.rule=PathPrefixStrip:/my-eureka"
    expose:
      - "8761"
    ports:
      - "8761:8761"

  my-zuul:
    image: peshou/gameit-zuul
    labels:
      - "traefik.port=8080"
      - "traefik.backend=my-zuul"
      - "traefik.frontend.rule=PathPrefixStrip:/my-zuul"

  my-gateway:
    image: peshou/gameit-gateway
    labels:
      - "traefik.port=8080"
      - "traefik.backend=my-gateway"
      - "traefik.frontend.rule=PathPrefixStrip:/my-gateway"

  my-mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbp4ss
      MYSQL_DATABASE: gameit
    volumes:
      - my-datavolume:/var/lib/mysql
    labels:
      - "traefik.enable=false"

  my-auth:
    image: peshou/gameit-auth
    labels:
      - "traefik.port=9999"
      - "traefik.backend=my-auth"
      - "traefik.frontend.rule=PathPrefixStrip:/my-auth"
    links:
      - my-mysql
      - my-eureka
      - my-zuul
      - my-gateway
    depends_on:
      - my-mysql
      - my-traefik
      - my-eureka
      - my-zuul
      - my-gateway
    environment:
      - DATABASE_HOST=my-mysql
      - DATABASE_USER=dbuser
      - DATABASE_PASSWORD=dbp4ss
      - DATABASE_NAME=gameit
      - DATABASE_PORT=3306

  my-app1:
    image: peshou/gameit1
    labels:
      - "traefik.port=8080"
      - "traefik.backend=my-app1"
      - "traefik.frontend.rule=PathPrefixStrip:/my-app1"
    links:
      - my-mysql
      - my-eureka
      - my-zuul
      - my-gateway
    depends_on:
      - my-mysql
      - my-traefik
      - my-eureka
      - my-zuul
      - my-gateway
    environment:
      - DATABASE_HOST=my-mysql
      - DATABASE_USER=dbuser
      - DATABASE_PASSWORD=dbp4ss
      - DATABASE_NAME=gameit
      - DATABASE_PORT=3306

  my-app2:
    image: peshou/gameit2
    labels:
      - "traefik.port=8080"
      - "traefik.backend=my-app2"
      - "traefik.frontend.rule=PathPrefixStrip:/my-app2"
    links:
      - my-mysql
      - my-eureka
      - my-zuul
      - my-gateway
    depends_on:
      - my-mysql
      - my-traefik
      - my-eureka
      - my-zuul
      - my-gateway
    environment:
      - DATABASE_HOST=my-mysql
      - DATABASE_USER=dbuser
      - DATABASE_PASSWORD=dbp4ss
      - DATABASE_NAME=gameit
      - DATABASE_PORT=3306

volumes:
  my-datavolume: {}
