version: '2'
services:
  my-traefik:
    image: traefik
    command: -c /dev/null --web --docker --docker.domain=dck.mojserver.mk
    labels:
      - "traefik.enable=false"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  my-eureka:
    image: peshou/gameit-eureka
    labels:
      - "traefik.port=8761"
      - "traefik.backend=my-eureka"
      - "traefik.frontend.rule=PathPrefixStrip:/my-eureka"
    expose:
      - "8761"
    ports:
      - "8761:8761"

  my-zuul:
    image: peshou/gameit-zuul
    labels:
      - "traefik.port=8080"
      - "traefik.backend=my-zuul"
      - "traefik.frontend.rule=PathPrefixStrip:/my-zuul"

  my-gateway:
    image: peshou/gameit-gateway
    labels:
      - "traefik.enabled=false"

  my-mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbp4ss
      MYSQL_DATABASE: gameit
    volumes:
      - my-datavolume:/var/lib/mysql
    labels:
      - "traefik.enable=false"

  my-auth:
    image: peshou/gameit-auth
    labels:
      - "traefik.enable=false"
    links:
      - my-mysql
      - my-eureka
    depends_on:
      - my-mysql
      - my-traefik
      - my-eureka
    environment:
      - DATABASE_HOST=my-mysql
      - DATABASE_USER=dbuser
      - DATABASE_PASSWORD=dbp4ss
      - DATABASE_NAME=gameit
      - DATABASE_PORT=3306

  my-app1:
    image: peshou/gameit1
    labels:
      - "traefik.enable=false"
    links:
      - my-mysql
      - my-eureka
    depends_on:
      - my-mysql
      - my-traefik
      - my-eureka
    environment:
      - DATABASE_HOST=my-mysql
      - DATABASE_USER=dbuser
      - DATABASE_PASSWORD=dbp4ss
      - DATABASE_NAME=gameit
      - DATABASE_PORT=3306
      - OAUTH_CLIENT_ID=gameit
      - OAUTH_CLIENT_SECRET=someSecret
      - OAUTH_TOKEN_VALIDITY=3600
      - STRIPE_TEST_PK=sk_test_qp9lcBPFPbDor0K5K8TaOR09
      - STRIPE_CLIENT_ID=ca_AQuIoAUDP9cVKHzEXtViIp4krfm0hIwQ

  my-mail:
    image: peshou/gameit-mail
    labels:
      - "traefik.enable=false"
    links:
      - my-mysql
      - my-eureka
    depends_on:
      - my-mysql
      - my-traefik
      - my-eureka
    environment:
      - MAIL_HOST=smtp.gmail.com
      - MAIL_USERNAME=eyo.adms@gmail.com
      - MAIL_PASSWORD=pesho123
      - MAIL_PORT=587
      - MAIL_TEST_CONNECTION=true
      - MAIL_AUTH=true
      - MAIL_SOCKET_PORT=25

volumes:
  my-datavolume: {}
