spring:
  profiles: default
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLInnoDBDialect
      ddl-auto: update
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gameit?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/