version: '2'
services:
  my-traefik:
    image: traefik
    command: -c /dev/null --web --docker --docker.domain=dck.mojserver.mk
    labels:
      - "traefik.enable=false"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  my-mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbp4ss
      MYSQL_DATABASE: demo
    volumes:
      - my-datavolume:/var/lib/mysql
    labels:
      - "traefik.enable=false"

  my-app:
    image: my_dockerhub_user/task4
    labels:
      - "traefik.port=8080"
      - "traefik.backend=my-app"
      - "traefik.frontend.rule=Host:my-app.dck.mojserver.mk"
    links:
      - my-mysql
    depends_on:
      - my-mysql
      - my-traefik

volumes:
  my-datavolume: {}
