spring:
  profiles: local
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT}
    test-connection: ${MAIL_TEST_CONNECTION}
    properties:
      mail:
        smtp:
          auth: ${MAIL_AUTH}
          socketFactory:
            port: ${MAIL_SOCKET_PORT}
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          ssl.enable: true
logging:
  level: debug
security:
  enable-csrf: false

eureka:
  client:
    service-url:
      defaultZone: http://my-eureka:8761/eureka/