spring:
  profiles: default
  mail:
    host: smtp.gmail.com
    username: eyo.adms@gmail.com
    password: pesho123
    port: 587
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 25
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          ssl.enable: true
gameit:
  oauth:
    client-id: gameit
    client-secret: someSecret
    token-validity-in-seconds: 3600
  stripe:
    testpk: sk_test_qp9lcBPFPbDor0K5K8TaOR09
    client-id: ca_AQuIoAUDP9cVKHzEXtViIp4krfm0hIwQ

logging:
  level: debug
security:
  enable-csrf: false
eureka:
  client:
    service-url:
      defaultZone: http://192.168.99.100:8761/eureka/
server:
  port: 8084