spring:
  profiles: local
  mvc:
    dispatch-options-request: true

eureka:
  client:
    service-url:
      defaultZone: http://my-eureka:8761/eureka/

zuul:
  ignoredServices: '*'
  routes:
    my-gateway:
      path: /my-gateway/**
      sensitive-headers:
    my-auth:
      path: /my-auth/**
      sensitive-headers:

management:
  security:
    enabled: false
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000
logging:
  level: debug
security:
  basic:
    enabled: false


