spring:
  profiles: default

eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/

# Configure the Authorization Server and User Info Resource Server details
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:9999/auth/oauth/token
      userAuthorizationUri: http://localhost:9999/auth/oauth/authorize
      clientId: myauthserver
      clientSecret: verysecretpassword
    resource:
      userInfoUri: http://localhost:9999/auth/user

zuul:
  ignoredServices: '*'
  routes:
    my-app1:
      url: http://localhost:8081
    my-app2:
      url: http://localhost:8082
    my-gateway:
      url: http://localhost:8083

# Make sure the OAuth2 token is only relayed when using the internal API,
# do not pass any authentication to the external API
proxy:
  auth:
    routes:
      my-app1: oauth2
      my-app2: oauth2
      my-gateway: oauth2

management:
  security:
    enabled: false
logging:
  level: debug
