spring:
  profiles: local
  mvc:
    dispatch-options-request: true

eureka:
  client:
    service-url:
      defaultZone: http://my-eureka:8761/eureka/
zuul:
  ignoredServices: '*'
  routes:
    my-gateway:
      path: /my-gateway/**
      sensitive-headers:
    my-auth:
      path: /my-auth/**
      sensitive-headers:
    my-games:
      path: /my-games/**
      sensitive-headers:
  ribbon-isolation-strategy: thread
  host:
    connect-timeout-millis: 60000 # starting the connection
    socket-timeout-millis: 60000  # monitor the continuous incoming data flow

management:
  security:
    enabled: false
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000
logging:
  level: debug
security:
  basic:
    enabled: false


