spring:
  profiles: default
  mvc:
    dispatch-options-request: true

eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/

zuul:
  ignoredServices: '*'
  routes:
    my-gateway:
      url: http://localhost:8083

management:
  security:
    enabled: false
logging:
  level: debug

security:
  basic:
    enabled: false
