spring:
  profiles: local
  mvc:
    dispatch-options-request: true

eureka:
  client:
    service-url:
     defaultZone: http://my-eureka:8761/eureka/

zuul:
  ignoredServices: '*'
  routes:
    my-gateway: /my-gateway/**
    my-auth:
       path: /my-auth/**
       sensitive-headers: true

management:
  security:
    enabled: false

logging:
  level: debug
security:
  basic:
    enabled: false


