version: '2'
services:
  my-traefik:
    image: traefik
    command: --web --docker=true --docker.domain="gameit.localhost" --logLevel=DEBUG
    labels:
      - "traefik.enable=false"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

  my-eureka:
    image: peshou/gameit-eureka
    labels:
      - "traefik.port=8761"
      - "traefik.backend=my-eureka"
      - "traefik.frontend.rule=Host:my-eureka.gameit.localhost"
    expose:
      - "8761"
    ports:
      - "8761:8761"

  my-mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbp4ss
      MYSQL_DATABASE: gameit
    volumes:
      - my-datavolume:/var/lib/mysql
    labels:
      - traefik.enable=false

  my-app:
    image: peshou/gameit
    labels:
      - traefik.port=8080
      - traefik.backend=my-app
      - traefik.frontend.rule=Host:my-app.gameit.localhost
    links:
      - my-mysql
      - my-eureka
    depends_on:
      - my-mysql
      - my-traefik
      - my-eureka
    environment:
      - DATABASE_HOST=my-mysql
      - DATABASE_USER=dbuser
      - DATABASE_PASSWORD=dbp4ss
      - DATABASE_NAME=gameit
      - DATABASE_PORT=3306
volumes:
  my-datavolume: {}
